#!/usr/bin/env bash
set -eux

sudo swapoff /dev/vg-root/swap
sudo umount -R /mnt

sudo vgchange -an vg1-data
sudo vgchange -an vg0-root

sudo cryptsetup close crypt_data
sudo cryptsetup close crypt_root

sudo reboot
